version: 0.2


phases:
  install:
    commands:
      # Update libs
      - apt-get update
      # Headless Chrome
      - apt-get install -y fonts-liberation libasound2 libnspr4 libnss3 libx11-xcb1 xdg-utils libxss1 libappindicator1 libindicator7
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - dpkg -i google-chrome*.deb
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build:ci
      - npm run test:ci || exit 0
  post_build:
     commands:
      # - if [ $CODEBUILD_BUILD_SUCCEEDING = "0" ]; then echo Build failed; exit 1; fi
      - "[ -d ./coverage ] && echo 'coverage directory found' && aws s3 sync ./coverage s3://codebuild-us-east-angular-front-dev/coverage/front --acl=public-read --exclude 'backups/*|'"
      - "aws s3 sync s3://codebuild-us-east-angular-front-dev/coverage/front/lcov-report/ s3://codebuild-us-east-angular-front-dev/coverage/front --acl=public-read --exclude 'backups/*|aws/*|sonarqube/*|linter/*|lcov.info' && aws s3 rm s3://codebuild-us-east-angular-front-dev/coverage/front/lcov-report/ --recursive"
      -  NOW=$(date +"%Y-%m-%d-%T")
      - "aws s3 cp s3://codebuild-us-east-angular-front-dev/coverage/front/ s3://codebuild-us-east-angular-front-dev/coverage/front/backups/$NOW --recursive --exclude 'backups'"
      - "[ -d ./dist ] && echo 'dist directory found' &&  aws s3 sync ./dist s3://codebuild-us-east-angular-front-dev --acl=public-read --exclude '.git/*|.coverage/front/*'"
      - npm run tslint:ci
      - node sonarqube-scan.js
      - echo Build completed on `date`
reports: #New
  CoverageReports: # CodeBuild will create a report group called "CoverageReports".
    files: #Store all of the files
      - '**/*'
    base-directory: 'coverage/aws' # Location of the reports 
artifacts:
  files:
      - 'dist/**/*'
      - 'coverage/**/*'
  base-directory: '.'